# This file is automatically generated.
# It contains project source information necessary for synthesis and implementation.

# IP: c:/Users/user/Desktop/final_complete/final_complete.srcs/sources_1/ip/VGAClk252/VGAClk252.xci
# IP: The module: 'VGAClk252' is the root of the design. Do not add the DONT_TOUCH constraint.

# XDC: c:/Users/user/Desktop/final_complete/final_complete.gen/sources_1/ip/VGAClk252/VGAClk252_board.xdc
# XDC: The top module name and the constraint reference have the same name: 'VGAClk252'. Do not add the DONT_TOUCH constraint.
set_property KEEP_HIERARCHY SOFT [get_cells inst -quiet] -quiet

# XDC: c:/Users/user/Desktop/final_complete/final_complete.gen/sources_1/ip/VGAClk252/VGAClk252.xdc
# XDC: The top module name and the constraint reference have the same name: 'VGAClk252'. Do not add the DONT_TOUCH constraint.
#dup# set_property KEEP_HIERARCHY SOFT [get_cells inst -quiet] -quiet

# XDC: c:/Users/user/Desktop/final_complete/final_complete.gen/sources_1/ip/VGAClk252/VGAClk252_late.xdc
# XDC: The top module name and the constraint reference have the same name: 'VGAClk252'. Do not add the DONT_TOUCH constraint.
#dup# set_property KEEP_HIERARCHY SOFT [get_cells inst -quiet] -quiet

# XDC: c:/Users/user/Desktop/final_complete/final_complete.gen/sources_1/ip/VGAClk252/VGAClk252_ooc.xdc
# XDC: The top module name and the constraint reference have the same name: 'VGAClk252'. Do not add the DONT_TOUCH constraint.
#dup# set_property KEEP_HIERARCHY SOFT [get_cells inst -quiet] -quiet

# IP: c:/Users/user/Desktop/final_complete/final_complete.srcs/sources_1/ip/VGAClk252/VGAClk252.xci
# IP: The module: 'VGAClk252' is the root of the design. Do not add the DONT_TOUCH constraint.

# XDC: c:/Users/user/Desktop/final_complete/final_complete.gen/sources_1/ip/VGAClk252/VGAClk252_board.xdc
# XDC: The top module name and the constraint reference have the same name: 'VGAClk252'. Do not add the DONT_TOUCH constraint.
#dup# set_property KEEP_HIERARCHY SOFT [get_cells inst -quiet] -quiet

# XDC: c:/Users/user/Desktop/final_complete/final_complete.gen/sources_1/ip/VGAClk252/VGAClk252.xdc
# XDC: The top module name and the constraint reference have the same name: 'VGAClk252'. Do not add the DONT_TOUCH constraint.
#dup# set_property KEEP_HIERARCHY SOFT [get_cells inst -quiet] -quiet

# XDC: c:/Users/user/Desktop/final_complete/final_complete.gen/sources_1/ip/VGAClk252/VGAClk252_late.xdc
# XDC: The top module name and the constraint reference have the same name: 'VGAClk252'. Do not add the DONT_TOUCH constraint.
#dup# set_property KEEP_HIERARCHY SOFT [get_cells inst -quiet] -quiet

# XDC: c:/Users/user/Desktop/final_complete/final_complete.gen/sources_1/ip/VGAClk252/VGAClk252_ooc.xdc
# XDC: The top module name and the constraint reference have the same name: 'VGAClk252'. Do not add the DONT_TOUCH constraint.
#dup# set_property KEEP_HIERARCHY SOFT [get_cells inst -quiet] -quiet
