# This file is automatically generated.
# It contains project source information necessary for synthesis and implementation.

# IP: C:/Users/Admin/Desktop/final_bb/final_complete.srcs/sources_1/ip/image_rom_1/image_rom.xci
# IP: The module: 'image_rom' is the root of the design. Do not add the DONT_TOUCH constraint.

# XDC: c:/Users/Admin/Desktop/final_bb/final_complete.gen/sources_1/ip/image_rom_1/image_rom_ooc.xdc
# XDC: The top module name and the constraint reference have the same name: 'image_rom'. Do not add the DONT_TOUCH constraint.
set_property KEEP_HIERARCHY SOFT [get_cells U0 -quiet] -quiet

# IP: C:/Users/Admin/Desktop/final_bb/final_complete.srcs/sources_1/ip/image_rom_1/image_rom.xci
# IP: The module: 'image_rom' is the root of the design. Do not add the DONT_TOUCH constraint.

# XDC: c:/Users/Admin/Desktop/final_bb/final_complete.gen/sources_1/ip/image_rom_1/image_rom_ooc.xdc
# XDC: The top module name and the constraint reference have the same name: 'image_rom'. Do not add the DONT_TOUCH constraint.
#dup# set_property KEEP_HIERARCHY SOFT [get_cells U0 -quiet] -quiet
