set_property IOSTANDARD LVCMOS33 [get_ports CLK_100M]
set_property IOSTANDARD LVCMOS33 [get_ports BTN_SOUTH]
set_property IOSTANDARD LVCMOS33 [get_ports BTN_WEST]
set_property IOSTANDARD LVCMOS33 [get_ports BTN_EAST]
set_property IOSTANDARD LVCMOS33 [get_ports LED[0]]
set_property IOSTANDARD LVCMOS33 [get_ports LED[1]]
set_property IOSTANDARD LVCMOS33 [get_ports LED[2]]
set_property IOSTANDARD LVCMOS33 [get_ports LED[3]]
set_property IOSTANDARD LVCMOS33 [get_ports LED[4]]
set_property IOSTANDARD LVCMOS33 [get_ports LED[5]]
set_property IOSTANDARD LVCMOS33 [get_ports LED[6]]
set_property IOSTANDARD LVCMOS33 [get_ports LED[7]]
set_property IOSTANDARD LVCMOS33 [get_ports switch[0]]
set_property IOSTANDARD LVCMOS33 [get_ports switch[1]]
set_property IOSTANDARD LVCMOS33 [get_ports switch[2]]
set_property IOSTANDARD LVCMOS33 [get_ports switch[3]]

set_property PACKAGE_PIN P17 [get_ports CLK_100M]
set_property PACKAGE_PIN R17  [get_ports BTN_SOUTH]
set_property PACKAGE_PIN R11  [get_ports BTN_EAST]
set_property PACKAGE_PIN V1  [get_ports BTN_WEST]
set_property PACKAGE_PIN K3  [get_ports LED[0]]
set_property PACKAGE_PIN M1  [get_ports LED[1]]
set_property PACKAGE_PIN L1  [get_ports LED[2]]
set_property PACKAGE_PIN K6  [get_ports LED[3]]
set_property PACKAGE_PIN J5  [get_ports LED[4]]
set_property PACKAGE_PIN H5  [get_ports LED[5]]
set_property PACKAGE_PIN G4  [get_ports LED[6]]
set_property PACKAGE_PIN F6  [get_ports LED[7]]


set_property PACKAGE_PIN R1  [get_ports switch[0]]
set_property PACKAGE_PIN N4  [get_ports switch[1]]
set_property PACKAGE_PIN M4  [get_ports switch[2]]
set_property PACKAGE_PIN R2  [get_ports switch[3]]