set_property IOSTANDARD LVCMOS33 [get_ports initial_clk]
set_property IOSTANDARD LVCMOS33 [get_ports initial_reset]
set_property IOSTANDARD LVCMOS33 [get_ports rotate_answer[0]]
set_property IOSTANDARD LVCMOS33 [get_ports rotate_answer[1]]
set_property IOSTANDARD LVCMOS33 [get_ports rotate_answer[2]]
set_property IOSTANDARD LVCMOS33 [get_ports rotate_answer[3]]
set_property IOSTANDARD LVCMOS33 [get_ports rotate_answer[4]]
set_property IOSTANDARD LVCMOS33 [get_ports rotate_answer[5]]
set_property IOSTANDARD LVCMOS33 [get_ports rotate_answer[6]]
set_property IOSTANDARD LVCMOS33 [get_ports rotate_answer[7]]

set_property PACKAGE_PIN P17 [get_ports initial_clk]
set_property PACKAGE_PIN R1  [get_ports initial_reset]

set_property PACKAGE_PIN K2  [get_ports rotate_answer[0]]
set_property PACKAGE_PIN J2  [get_ports rotate_answer[1]]
set_property PACKAGE_PIN J3  [get_ports rotate_answer[2]]
set_property PACKAGE_PIN H4  [get_ports rotate_answer[3]]
set_property PACKAGE_PIN J4  [get_ports rotate_answer[4]]
set_property PACKAGE_PIN G3  [get_ports rotate_answer[5]]
set_property PACKAGE_PIN G4  [get_ports rotate_answer[6]]
set_property PACKAGE_PIN F6  [get_ports rotate_answer[7]]
