# This file is automatically generated.
# It contains project source information necessary for synthesis and implementation.

# IP: C:/Users/user/Desktop/final_bb/final_complete.srcs/sources_1/ip/image_rom2/image_rom2.xci
# IP: The module: 'image_rom2' is the root of the design. Do not add the DONT_TOUCH constraint.

# XDC: c:/Users/user/Desktop/final_bb/final_complete.gen/sources_1/ip/image_rom2/image_rom2_ooc.xdc
# XDC: The top module name and the constraint reference have the same name: 'image_rom2'. Do not add the DONT_TOUCH constraint.
set_property KEEP_HIERARCHY SOFT [get_cells U0 -quiet] -quiet

# IP: C:/Users/user/Desktop/final_bb/final_complete.srcs/sources_1/ip/image_rom2/image_rom2.xci
# IP: The module: 'image_rom2' is the root of the design. Do not add the DONT_TOUCH constraint.

# XDC: c:/Users/user/Desktop/final_bb/final_complete.gen/sources_1/ip/image_rom2/image_rom2_ooc.xdc
# XDC: The top module name and the constraint reference have the same name: 'image_rom2'. Do not add the DONT_TOUCH constraint.
#dup# set_property KEEP_HIERARCHY SOFT [get_cells U0 -quiet] -quiet
